# Generated by Django 3.2.9 on 2021-11-23 12:51

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=25)),
                ('body', models.TextField()),
                ('date', models.CharField(default=todo_app.models.getday, max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
